volumes:
  horde-db:
  horde-turba:
  horde-nag:
  horde-ingo:
  horde-mnemo:
  horde-horde:
  horde-imp:
  horde-kronolith:
services:
  horde:
    build: .
    environment:
      HORDE_SQL_USERNAME: root
      HORDE_SQL_PASSWORD: thBOL4SIF83zBOXbwzRiBrv200hiG2
      HORDE_SQL_HOST: db
      HORDE_SQL_DATABASE: horde
      HORDE_SQL_PORT: 3306
      IMP_HOSTSPEC: mail.ibs-swissrealestate.com
      IMP_MAILDOMAIN: ibs-swissrealestate.com
      IMP_HORDEAUTH: 'true'
      IMP_PROTOCOL: 'imap'
      IMP_SECURE: 'ssl'
      IMP_PORT: 993
      INGO_IMAP_DISABLED: 'false'
      INGO_SIEVE_DISABLED: 'true'
      HORDE_THEME: 'knttheme'
      HORDE_THEME_LOCKED: 'true'
    restart: unless-stopped
    links:
      - db
      - memcached
    ports:
      - "8981:80"
    volumes:
    - horde-turba:/var/www/html/horde/turba/config
    - horde-nag:/var/www/html/horde/nag/config
    - horde-ingo:/var/www/html/horde/ingo/config
    - horde-mnemo:/var/www/html/horde/mnemo/config
    - horde-horde:/var/www/html/horde/config
    - horde-imp:/var/www/html/horde/imp/config
    - horde-kronolith:/var/www/html/horde/kronolith/config
    networks:
      - internal
      - web
    labels:
      - traefik.http.routers.ibs-horde.rule=Host(`ibs-horde.uxq.ch`)
      - traefik.http.routers.ibs-horde.tls=true
      - traefik.http.routers.ibs-horde.tls.certresolver=myresolver
      - traefik.docker.network=web
      - traefik.port=80
  memcached:
    image: memcached:1.5-alpine
    networks:
      - internal
    labels:
      - traefik.enable=false
    restart: unless-stopped
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: thBOL4SIF83zBOXbwzRiBrv200hiG2
      MYSQL_DATABASE: horde
    command: --max_allowed_packet=32505856
    networks:
      - internal
    volumes:
      - horde-db:/var/lib/mysql
    labels:
      - traefik.enable=false
    restart: unless-stopped

networks:
  web:
    external: true
  internal:
    external: false

