volumes:
  horde-db:
  horde-turba:
  horde-nag:
  horde-ingo:
  horde-mnemo:
  horde-horde:
  horde-imp:
  horde-kronolith:
services:
  horde:
    build: .
    environment:
      HORDE_SQL_USERNAME: root
      HORDE_SQL_PASSWORD: WoDerRootlyDeMoschtHolt
      HORDE_SQL_HOST: db
      HORDE_SQL_DATABASE: horde
      IMP_HOSTSPEC: vodka.vrtz.ch
      IMP_MAILDOMAIN: uxw.ch
      INGO_SIEVE_HOST: vodka.vrtz.ch
      INGO_SIEVE_USETLS: 'false'
      HORDE_THEME: 'knttheme'
      HORDE_THEME_LOCKED: 'true'
    restart: on-failure
    links:
      - db
      - memcached
    ports:
      - "8982:80"
    volumes:
    - horde-turba:/var/www/html/horde/turba/config
    - horde-nag:/var/www/html/horde/nag/config
    - horde-ingo:/var/www/html/horde/ingo/config
    - horde-mnemo:/var/www/html/horde/mnemo/config
    - horde-horde:/var/www/html/horde/config
    - horde-imp:/var/www/html/horde/imp/config
    - horde-kronolith:/var/www/html/horde/kronolith/config
    networks:
      - internal
      - web
    labels:
      - traefik.http.routers.hordeplayground.rule=Host(`hordeplayground.uxw.ch`)
      - traefik.http.routers.hordeplayground.tls=true
      - traefik.http.routers.hordeplayground.tls.certresolver=myresolver
      - traefik.docker.network=web
      - traefik.port=80
  memcached:
    image: memcached:1.5-alpine
    networks:
      - internal
    labels:
      - traefik.enable=false
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: WoDerRootlyDeMoschtHolt
      MYSQL_DATABASE: horde
    command: --max_allowed_packet=32505856
    networks:
      - internal
    volumes:
      - horde-db:/var/lib/mysql
    labels:
      - traefik.enable=false

networks:
  web:
    external: true
  internal:
    external: false

